version: 0.0
os: linux
files:
  - source: /
    destination: /app/mern-app
permissions:
  - object: /app/mern-app
    owner: ubuntu
    group: ubuntu
    type:
      - file
      - directory
hooks:  
  BeforeInstall:
    - location: deployment-scripts/BeforeInstall.sh
      timeout: 120
      runas: ubuntu
  ApplicationStop:
    - location: deployment-scripts/Appstop.sh   
      timeout: 120    
      runas: ubuntu
  ApplicationStart:
    - location: deployment-scripts/Appstart.sh
      timeout: 120
      runas: ubuntu
  ValidateService:
    - location: deployment-scripts/ValidateService.sh
      timeout: 120
      runas: ubuntu
